steps:
  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','./go']
    env: ['GOPATH=.','CGO_ENABLED=0']

  - id: go_build
    name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', './go', './go']
    env: ['GOPATH=.']

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/challenge-k8s-go:latest', './go/']

images:
  - 'gcr.io/$PROJECT_ID/challenge-k8s-go:latest'