steps:
  - id: go_test
    name: 'gcr.io/cloud-builders/go'
    args: ['test','./go']
    env: ['GOPATH=.','CGO_ENABLED=0']

  - id: go_build
    name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', './go', './go']
    env: ['GOPATH=.']

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/$PROJECT_ID/challenge-k8s-go:$SHORT_SHA', './go/']

  - id: "Pushing image"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/challenge-k8s-go:$SHORT_SHA']

  - id: "Adjusting deployenmt file - Kubernetes"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args: 
      - '-c'
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/challenge-k8s-go:$SHORT_SHA#g' k8s/app/deployment.yaml > k8s/app/deployment-new.yaml;
        cat k8s/app/deployment-new.yaml
  - id: "Deploying kubernetes"
    name: 'gcr.io/cloud-builders/kubectl'
    args: 
      - 'apply'
      - '-f'
      - 'k8s/app/'
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'